spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/megnarealestate?createDatabaseIfNotExist=true
    username: root
    password: SpiderMan1133
  jpa:
    show-sql: true